# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mount/data/home/staff/grabner/subversion/stb4/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mount/data/home/staff/grabner/subversion/stb4/trunk

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake

# Special rule for the target install/local
install/local/fast: install/local

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config /mount/data/home/staff/grabner/subversion/stb4/trunk/CPackConfig.cmake

# Special rule for the target package
package/fast: package

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config /mount/data/home/staff/grabner/subversion/stb4/trunk/CPackSourceConfig.cmake

# Special rule for the target package_source
package_source/fast: package_source

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mount/data/home/staff/grabner/subversion/stb4/trunk/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mount/data/home/staff/grabner/subversion/stb4/trunk/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build

#=============================================================================
# Target rules for targets named workspace

# Build rule for target.
workspace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 workspace

# fast build rule for target.
workspace/fast:
	$(MAKE) -f src/bootloader/CMakeFiles/workspace.dir/build.make src/bootloader/CMakeFiles/workspace.dir/build

#=============================================================================
# Target rules for targets named stbevent

# Build rule for target.
stbevent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stbevent

# fast build rule for target.
stbevent/fast:
	$(MAKE) -f src/components/event/CMakeFiles/stbevent.dir/build.make src/components/event/CMakeFiles/stbevent.dir/build

#=============================================================================
# Target rules for targets named stbstarlight

# Build rule for target.
stbstarlight: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stbstarlight

# fast build rule for target.
stbstarlight/fast:
	$(MAKE) -f src/components/starlight/CMakeFiles/stbstarlight.dir/build.make src/components/starlight/CMakeFiles/stbstarlight.dir/build

#=============================================================================
# Target rules for targets named stbvideo

# Build rule for target.
stbvideo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stbvideo

# fast build rule for target.
stbvideo/fast:
	$(MAKE) -f src/components/video/CMakeFiles/stbvideo.dir/build.make src/components/video/CMakeFiles/stbvideo.dir/build

#=============================================================================
# Target rules for targets named stbviewer_qt

# Build rule for target.
stbviewer_qt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stbviewer_qt

# fast build rule for target.
stbviewer_qt/fast:
	$(MAKE) -f src/components/viewer/CMakeFiles/stbviewer_qt.dir/build.make src/components/viewer/CMakeFiles/stbviewer_qt.dir/build

#=============================================================================
# Target rules for targets named stbkernel

# Build rule for target.
stbkernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stbkernel

# fast build rule for target.
stbkernel/fast:
	$(MAKE) -f src/kernel/CMakeFiles/stbkernel.dir/build.make src/kernel/CMakeFiles/stbkernel.dir/build

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... clean-all"
	@echo "... dist"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... workspace"
	@echo "... stbevent"
	@echo "... stbstarlight"
	@echo "... stbvideo"
	@echo "... stbviewer_qt"
	@echo "... stbkernel"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

