Import('env')

conf = Configure(env)

#****************************************************************************
# Make sure Qt is available
#****************************************************************************
if conf.TryAction('pkg-config --exists qt-mt')[0]:
    env.ParseConfig('pkg-config --cflags --libs qt-mt')
else:
    print "****************************************************************************"
    print "WARNING: You need to have QT installed for using the viewer module"
    print "****************************************************************************"

#****************************************************************************
# Make sure SoQt is available
#****************************************************************************
if conf.TryAction('soqt-config')[0]:
    env.ParseConfig('soqt-config --cxxflags --libs')
else:
    print "****************************************************************************"
    print "WARNING: You need to have SoQt installed for using the viewer module"
    print "****************************************************************************"

conf.Finish()

stb_lib    = env.SharedLibrary(env['STB_LIB_NAME'], env['SOURCE_FILES'])
env.Alias(target = ['install'], source = env.Install(dir = '${INSTALLDIR}/lib', source = stb_lib))
