" \
float4 main(float4 wpos:WPOS, float4 color0:COLOR0, uniform samplerRECT ZTexture):COLOR \n\
{ \n\
	float4 outputColor; \n\
	float2 xyFragmentPosition; \n\
	float4 zTextureValues; \n\
	xyFragmentPosition=wpos.xy; \n\
	zTextureValues=texRECT(ZTexture, xyFragmentPosition); \n\
	outputColor=color0; \n\
	if ((wpos.z<zTextureValues.x)||(wpos.z>zTextureValues.y)) \n\
		discard; \n\
	return outputColor; \n\
} \n\
"
