#!/usr/bin/python
import os
import buildutils

#!/usr/bin/python
Import ('user_options_dict')
Import ('library_env')
Import ('env')

header_env = library_env.Copy ()

# Search for data files
datadir   = Dir('#').abspath + os.sep + 'data'
datafiles = buildutils.listtrav(datadir, datadir, True)
datafiles = buildutils.regexpfilter(datafiles, user_options_dict['IGNORE_FILTER'], False)

# Install data files
for data in datafiles:
    print data
    dirname = data[0:data.rindex(os.sep)]
    print dirname
    env.Alias(target = ['install'], source = header_env.Install(user_options_dict['INSTALL_ROOT_DIR'] + os.sep + user_options_dict['PREFIX'] + os.sep + 'share/stb/applications' + os.sep + dirname, datadir + os.sep + data))
