#!/usr/bin/python
import sys
import os
import buildutils

Import ('user_options_dict')
Import ('library_env')
Import ('env')

simple_env = library_env.Copy ()

# Get all files from directory while applying ignore filter
source_dir   = Dir('#').abspath + os.sep + '/src/applications/simple'
source_files = buildutils.listtrav(source_dir, source_dir)
source_files = buildutils.regexpfilter(source_files, user_options_dict['SOURCE_FILTER'], True)
source_files = buildutils.regexpfilter(source_files, user_options_dict['IGNORE_FILTER'], False)

# Coin
simple_env.Append (CPPPATH = user_options_dict['COIN_INCLUDE'])
simple_env.Append (LIBPATH = user_options_dict['COIN_LIBPATH'])
simple_env.Append (LIBS    = user_options_dict['COIN_LIBRARY'])

simple = simple_env.SharedLibrary (target='#'+user_options_dict['BUILD_DIR']+'/lib/stbsimple', source=source_files)
env.Alias(target = ['install'], source = simple_env.Install(user_options_dict['INSTALL_ROOT_DIR'] + os.sep + user_options_dict['LIBDIR'], simple))
